apiVersion: v1
kind: Service
metadata:
  name: broadcasts-service
spec:
  type: NodePort
  selector:
    app: view-broadcasts
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30005
